worker/app.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_babelex import Babel
from blueprints.competency import competency_page
from blueprints.work import work_page
from blueprints.employer import employer_page
from blueprints.main import main_page
from blueprints.manage_competencies import manage_competencies_page
from blueprints.demanded_competencies import demanded_competencies_page
from blueprints.best_works import best_works_page
import security

app = Flask(__name__)
app.config.from_pyfile('config.py')
babel = Babel(app)
bootstrap = Bootstrap(app)
security.configure(app)
mail = Mail(app)

app.register_blueprint(competency_page)
app.register_blueprint(work_page)
app.register_blueprint(employer_page)
app.register_blueprint(main_page)
app.register_blueprint(manage_competencies_page)
app.register_blueprint(demanded_competencies_page)
app.register_blueprint(best_works_page)


# в comp_table.html требуется проверять наличие элементов в списке
# этот метод преобразует список в словарь, чтобы такие проверки можно было делать эффективно
@app.template_filter('to_set')
def to_set_filter(competencies):
    if competencies is None:
        return None
    return {x['id']: 1 for x in competencies}


if __name__ == '__main__':
    app.run(port=5003)

worker/blueprints/best_works.py
from flask import Blueprint, render_template
from services_info import get_current_user, get_best_works
from flask_security import login_required

best_works_page = Blueprint('best_works_page', __name__, template_folder='templates')


@best_works_page.route('/best_works')
@login_required
def best_works():
    user = get_current_user()
    return render_template("best_works.html", user=user, best_works=get_best_works(user['id']))

worker/blueprints/competency.py
from flask import Blueprint, jsonify, render_template
from services_info import get_current_user, get_competency
from flask_security import login_required
from .competency_table import change_competency_func

competency_page = Blueprint('competency_page', __name__, template_folder='templates')


@competency_page.route('/competency/<int:comp_id>')
@login_required
def competency(comp_id: int):
    return render_template("competency.html", user=get_current_user(), competency=get_competency(comp_id))


@competency_page.route('/change_competency_1', methods=['POST'])
@login_required
def change_competency_1():
    return jsonify(is_added=change_competency_func())

worker/blueprints/competency_table.py
from flask import render_template_string, jsonify, request
from services_info import append_comp_to_worker, remove_comp_from_worker, get_current_user, get_current_user_id


def render_table(view_competencies, added_competencies):
    print(view_competencies)
    print(added_competencies)
    return render_template_string(
        "{% import 'comp_table.html' as macro %}{{ macro.table(view_competencies, added_competencies) }}",
        view_competencies=view_competencies,
        added_competencies=added_competencies)


def change_competency_func():
    form = request.form
    request_type = form.get('type', 0, type=str)
    comp_id = form.get('comp_id', 0, type=int)
    user_id = get_current_user_id()
    if request_type == 'append':
        append_comp_to_worker(user_id, comp_id)
        return True
    elif request_type == 'remove':
        remove_comp_from_worker(user_id, comp_id)
        return False


def load_table(blueprint, path):
    def decorator(get_comps):
        @blueprint.route(path + '/change_competency', methods=['POST'])
        def change_competency(**kwargs):
            change_competency_func()
            return jsonify(table=render_table(get_comps(**kwargs), get_current_user()['competencies']))
        return change_competency
    return decorator

worker/blueprints/demanded_competencies.py
from flask import Blueprint, render_template
from services_info import get_current_user, get_current_user_id, get_demanded_competencies, get_competency
from blueprints.competency_table import load_table
from flask_security import login_required

demanded_competencies_page = Blueprint('demanded_competencies_page', __name__, template_folder='templates')


def get_demanded_comps():
    return [get_competency(comp_id) for comp_id in get_demanded_competencies(get_current_user_id())]


@demanded_competencies_page.route('/demanded_competencies')
@login_required
def demanded_competencies():
    return render_template("demanded_competencies.html", user=get_current_user(), demanded_competencies=get_demanded_comps())


@load_table(demanded_competencies_page, '/demanded_competencies')
@login_required
def change_competency():
    return get_demanded_comps()

worker/blueprints/main.py
from flask import Blueprint, render_template, redirect, url_for
from services_info import get_current_user, get_professions, get_areas
from flask_security import login_required, logout_user

main_page = Blueprint('main_page', __name__, template_folder='templates')


@main_page.route('/')
@login_required
def index():
    return render_template("index.html", user=get_current_user(), professions=get_professions(), areas=get_areas())


@main_page.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('/'))

worker/blueprints/manage_competencies.py
from flask import Blueprint, render_template, jsonify, request, render_template_string
from services_info import get_current_user, get_professions, get_competencies, get_areas, get_area_profs
from blueprints.competency_table import render_table, change_competency_func
from flask_security import login_required

manage_competencies_page = Blueprint('manage_competencies_page', __name__, template_folder='templates')


@manage_competencies_page.route('/manage_competencies')
@login_required
def manage_competencies():
    return render_template("manage_competencies.html", user=get_current_user(), professions=get_professions(), areas=get_areas())


def get_found_comps():
    form = request.form
    prof_id = form.get('prof_id', 0, type=int)
    area_id = form.get('area_id', 0, type=int)
    description = form.get('description', None, type=str)
    return get_competencies(area_id, prof_id, description)


@manage_competencies_page.route('/change_competency', methods=['POST'])
@login_required
def change_competency():
    change_competency_func()
    found_comps = get_found_comps()
    user_comps = get_current_user()['competencies']
    return jsonify(
        found_comp_table=render_table(found_comps, user_comps),
        user_comp_table=render_table(user_comps, None)
    )


_option_template = "{% import 'profession_select.html' as macro %}{{ macro.profession_select(professions, disabled) }}"


@manage_competencies_page.route('/get_prof_comps', methods=['POST'])
@login_required
def get_prof_comps():
    form = request.form
    area_id = form.get('area_id', 0, type=int)
    update_prof = form.get('update_prof', False, type=bool)

    user_comps = get_current_user()['competencies']
    found_comp_table = render_table(get_found_comps(), user_comps)

    if update_prof:
        return jsonify(
            found_comp_table=found_comp_table,
            prof_select=render_template_string(_option_template, professions=get_area_profs(area_id), disabled=area_id == 0)
        )
    else:
        return jsonify(found_comp_table=found_comp_table)

worker/blueprints/work.py
from flask import Blueprint, render_template
from services_info import get_work_info, get_current_user
from blueprints.competency_table import load_table
from flask_security import login_required

work_page = Blueprint('work_page', __name__, template_folder='templates')


@work_page.route('/work/<int:work_id>')
@login_required
def work(work_id: int):
    return render_template("work.html", user=get_current_user(), work=get_work_info(work_id))


@load_table(work_page, '/work/<int:work_id>')
@login_required
def change_competency(work_id: int):
    return get_work_info(work_id)['competencies']

worker/templates/best_works.html
{% extends "base.html" %}
{% import 'works_table.html' as macro %}

{% block title %}
    Подходящие вакансии
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Наиболее подходящие вакансии</h3>
        <div>
            {{ macro.table(best_works) }}
        </div>
    </div>
{% endblock %}

worker/templates/comp_table.html
{% macro div_table(view_competencies, added_competencies, div_name='competencies_table') %}
<div id="{{ div_name }}">
    {{ table(view_competencies, added_competencies) }}
</div>
{% endmacro %}

{% macro table(view_competencies, added_competencies, active=true) %}
{% if view_competencies %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Компетенция</th>
            <th>Индикаторы компетенции</th>
            {% if active %}
            <th></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% set added_competencies = added_competencies | to_set %}
        {% for competency in view_competencies %}
        <tr>
            <td><a href="{{ url_for('competency_page.competency', comp_id=competency.id) }}">{{ competency.name }}</a></td>
            <td>
            <ul style="list-style-position: inside; padding-left: 0;">
                {% for indicator in competency.indicators[:5] %}
                    <li>{{ indicator }}</li>
                {% endfor %}
            </ul>
            </td>
            {% if active %}
            <td>
                {% if added_competencies is none or competency.id in added_competencies %}
                    <button class="btn btn-default" type="button" onclick="change_competency('remove', {{ competency.id }})">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <span><strong>Удалить</strong></span>
                    </button>
                {% else %}
                    <button class="btn btn-default" type="button" onclick="change_competency('append', {{ competency.id }})">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        <span><strong>Добавить</strong></span>
                    </button>
                {% endif %}
            </td>
            {% endif %}
        </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>Выбранные компетенции отсутствуют</p>
{% endif %}
{% endmacro %}

{% macro table_changed(div_name='competencies_table') %}
<script>
    function change_competency(type, comp_id) {
        $.ajax({
            method: 'POST',
            url: '{{ request.path }}/change_competency',
            data: {type: type, comp_id: comp_id}
        }).done(function(data){
            $('#{{ div_name }}').html(data.table);
        });
    }
</script>
{% endmacro %}

worker/templates/competency.html
{% extends "base.html" %}

{% block title %}
    Компетенция &mdash; {{ competency.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Компетенция &mdash; {{ competency.name }}</h3>

        <ul>
        {% for indicator in competency.indicators %}
            <li>{{ indicator }}</li>
        {% endfor %}
        </ul>

        {% set added = (competency.id in (user.competencies | to_set)) %}

        <div id="is_added" {% if not added %} style="display:none;" {% endif %}>
            <p>Вы владеете данной компетенцией</p>
            <button class="btn btn-default" type="button" onclick="change_competency('remove', {{ competency.id }})">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <span><strong>Удалить</strong></span>
            </button>
        </div>
        <div id="is_not_added" {% if added %} style="display:none;" {% endif %}>
            <p>Вы не владеете данной компетенцией</p>
            <button class="btn btn-default" type="button" onclick="change_competency('append', {{ competency.id }})">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <span><strong>Добавить</strong></span>
            </button>
        </div>

    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type=text/javascript>
        function change_competency(type, comp_id) {
            console.log(type + ': ' + comp_id);
            $.ajax({
                method: 'POST',
                url: {{ url_for('competency_page.change_competency_1')|tojson }},
                data: {type: type, comp_id: comp_id}
            }).done(function(data) {
                let is_added = data.is_added;
                $('#is_added').toggle(is_added);
                $('#is_not_added').toggle(!is_added);
            });
        }
    </script>
{% endblock %}

worker/templates/demanded_competencies.html
{% extends "base.html" %}
{% import 'comp_table.html' as macro %}

{% block title %}
    Рекомендуемые к изучению компетенции
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Рекомендуемые к изучению компетенции</h3>
        {{ macro.div_table(demanded_competencies, user.competencies) }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ macro.table_changed() }}
{% endblock %}

worker/templates/index.html
{% extends "base.html" %}
{% import 'comp_table.html' as macro %}

{% block title %}
    Система управления компетенциями
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Здравствуй, {{ user.name }}!</h2>

        <div class="btn-group-vertical">
            <a href="{{ url_for('manage_competencies_page.manage_competencies') }}" class="btn btn-default">
                <strong>Выбрать мои компетенции</strong>
            </a>
            <a href="{{ url_for('best_works_page.best_works') }}" class="btn btn-default">
                <strong>Найти наиболее подходящие вакансии</strong>
            </a>
            <a href="{{ url_for('demanded_competencies_page.demanded_competencies') }}" class="btn btn-default">
                <strong>Получить рекомендации к изучению компетенций</strong>
            </a>
        </div>

        <h3>Ваши компетенции</h3>
        {{ macro.table(user.competencies, none, false) }}

    </div>
{% endblock %}

worker/templates/manage_competencies.html
{% extends "base.html" %}
{% import 'comp_table.html' as comp_table %}
{% import 'profession_select.html' as prof_select %}

{% block title %}
    Система управления компетенциями
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Ваши компетенции</h3>
        {{ comp_table.div_table(user.competencies, none, 'user_comp_table') }}

        <h3>Поиск компетенций</h3>
        <div class="form-group">
            <select id="area-selector" class="form-control">
                <option value="0">Выберите профессиональную область</option>
                {% for area in areas %}
                    <option value="{{ area.id }}">{{ area.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div id="prof-selector-div" class="form-group"></div>
        <div class="form-group">
            <textarea id="comp-text" class="form-control" placeholder="Введите описание компетенции своими словами"></textarea>
        </div>
        <div class="form-group">
            <button id="search-button" class="btn btn-default" type="button" onclick="on_prof_selector_change()">Поиск</button>
        </div>

        {{ comp_table.div_table([], none, 'found_comp_table') }}

    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type=text/javascript>
        $('#prof-selector').change(on_prof_selector_change);
        $('#area-selector').change(on_area_selector_change).change();

        function on_prof_selector_change() {
            let data = {prof_id: $('#prof-selector').val(), area_id: $('#area-selector').val(), description: $('#comp-text').val()};
            ajax_update_tables(data);
        }

        function on_area_selector_change() {
            let data = {area_id: $('#area-selector').val(), update_prof: true, description: $('#comp-text').val()};
            ajax_update_tables(data);
        }

        function ajax_update_tables(data) {
            $('#search-button').prop("disabled", true);
            $.ajax({
                method: 'POST',
                url: {{ url_for('manage_competencies_page.get_prof_comps')|tojson }},
                data: data
            }).done(update_tables);
        }

        function update_tables(data) {
            $('#found_comp_table').html(data.found_comp_table);
            if (data.hasOwnProperty('user_comp_table')) {
                $('#user_comp_table').html(data.user_comp_table);
            }
            if (data.hasOwnProperty('prof_select')) {
                $('#prof-selector-div').html(data.prof_select);
                $('#prof-selector').change(on_prof_selector_change);
            }
            $('#search-button').prop("disabled", false);
        }

        function change_competency(type, comp_id) {
            $('#search-button').prop("disabled", true);
            $.ajax({
                method: 'POST',
                url: {{ url_for('manage_competencies_page.change_competency')|tojson }},
                data: {type: type, comp_id: comp_id, prof_id: $('#prof-selector').val(), area_id: $('#area-selector').val()}
            }).done(update_tables);
        }
    </script>
{% endblock %}

worker/templates/security/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main_page.index') }}">Компетентностная система</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% if security.registerable or security.recoverable or security.confirmable %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Войти</a></li>
                    {% if security.registerable %}
                    <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Зарегистрироваться</a></li>
                    {% endif %}
                    {% if security.recoverable %}
                    <li><a href="{{ url_for_security('forgot_password') }}">Забыли пароль?</a></li>
                    {% endif %}
                    {% if security.confirmable %}
                    <li><a href="{{ url_for_security('send_confirmation') }}">Подтвердить аккаунт</a></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
		{{ content }}
        {% block form_content %}{% endblock %}
    </div>
    <div class="col-xs-2"></div>
</div>
{% endblock %}

worker/templates/security/register_user.html
{% extends "security/base.html" %}

{% block title %}
Зарегистрироваться как соискатель
{% endblock %}

{% block form_content %}
<h2>Зарегистрироваться как соискатель</h2>
<form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
    {{ register_user_form.hidden_tag() }}
    {{ wtf.form_field(register_user_form.full_name) }}
    {{ wtf.form_field(register_user_form.email) }}
    {{ wtf.form_field(register_user_form.password) }}
    {% if register_user_form.password_confirm %}
    {{ wtf.form_field(register_user_form.password_confirm) }}
    {% endif %}
    {{ wtf.form_field(register_user_form.submit) }}
</form>
{% endblock %}

worker/templates/work.html
{% extends "base.html" %}
{% import 'comp_table.html' as macro %}

{% block title %}
    Вакансия &mdash; {{ work.description }}
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Вакансия &mdash; {{ work.description }}</h3>

        <p><b>Зарплата:</b> {{ work.salary }}₽</p>
        <p><b>Работодатель:</b> <a href="{{ url_for('employer_page.employer', employer_id=work.employer.id) }}">{{ work.employer.name }}</a></p>

        <h4>Требуемые для вакансии компетенции</h4>
        {{ macro.div_table(work.competencies, user.competencies) }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ macro.table_changed() }}
{% endblock %}

worker/templates/works_table.html
{% macro table(works) %}
{% if works %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Вакансия</th>
            <th>Необходимые компетенции</th>
            <th>Зарплата</th>
        </tr>
    </thead>
    <tbody>
    {% for work in works %}
        <tr>
            <td><a href="{{ url_for('work_page.work', work_id=work.id) }}">{{ work.description }}</a></td>
            <td>
                <ul style="list-style-position: inside; padding-left: 0;">
                {% for competency in work.competencies %}
                    <li><a href="{{ url_for('competency_page.competency', comp_id=competency.id) }}">{{ competency.name }}</a></li>
                {% endfor %}
                </ul>
            </td>
            <td>{{ work.salary }}₽</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Вакансии отсутствуют</p>
{% endif %}
{% endmacro %}