employer/blueprints/add_work.py
from flask import Blueprint, redirect, render_template
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, NumberRange
from flask_security import login_required
from services_info import get_current_user, get_current_user_id, add_work as add_work_

add_work_page = Blueprint('add_work_page', __name__, template_folder='templates')


class AddWorkForm(FlaskForm):
    description = StringField('Название вакансии', validators=[DataRequired()])
    salary = IntegerField('Зарплата', validators=[NumberRange(min=1)])
    submit = SubmitField('Создать вакансию')


@add_work_page.route('/add_work', methods=('GET', 'POST'))
@login_required
def add_work():
    form = AddWorkForm()
    if form.validate_on_submit():
        work_id = add_work_(get_current_user_id(), form.description.data, form.salary.data)
        return redirect('/work/%d' % work_id)
    return render_template('add_work.html', user=get_current_user(), form=form)

employer/blueprints/best_workers.py
from flask import Blueprint, render_template
from services_info import get_current_user, get_best_workers
from flask_security import login_required

best_workers_page = Blueprint('best_workers_page', __name__, template_folder='templates')


@best_workers_page.route('/best_workers/<int:work_id>')
@login_required
def best_workers(work_id: int):
    return render_template("best_workers.html", user=get_current_user(), best_workers=get_best_workers(work_id), work_id=work_id)

employer/blueprints/competency.py
from flask import Blueprint, jsonify, render_template, request
from services_info import get_current_user, get_competency, get_work_info
from .competency_table import change_competency_func
from flask_security import login_required

competency_page = Blueprint('competency_page', __name__, template_folder='templates')


@competency_page.route('/competency/<int:comp_id>')
@login_required
def competency(comp_id: int):
    work_id = request.args.get('work', 0, type=int)
    work = get_work_info(work_id, load_comps=False) if work_id else None
    return render_template("competency.html", user=get_current_user(), competency=get_competency(comp_id), work=work)


@competency_page.route('/change_competency_1', methods=['POST'])
@login_required
def change_competency_1():
    return jsonify(is_added=change_competency_func())

employer/blueprints/competency_table.py
from flask import render_template_string, jsonify, request
from services_info import append_comp_to_work, remove_comp_from_work, get_work_info


def get_current_work(from_args: bool = False):
    if from_args:
        work_id = request.args.get('work', 0, type=int)
        if not work_id:
            return None
    else:
        work_id = request.form.get('work_id', 0, type=int)
    return get_work_info(work_id)


def render_table(view_competencies, work):
    if view_competencies is None:
        view_competencies = work['competencies']
        added_competencies = None
    else:
        added_competencies = work['competencies']
    return render_template_string(
        "{% import 'comp_table.html' as macro %}{{ macro.table(view_competencies, added_competencies, work_id=work_id) }}",
        view_competencies=view_competencies,
        added_competencies=added_competencies,
        work_id=work['id'])


def change_competency_func():
    form = request.form
    request_type = form.get('type', 0, type=str)
    comp_id = form.get('comp_id', 0, type=int)
    work_id = form.get('work_id', 0, type=int)

    if request_type == 'append':
        append_comp_to_work(work_id, comp_id)
        return True
    elif request_type == 'remove':
        remove_comp_from_work(work_id, comp_id)
        return False


def load_table(blueprint, path):
    def decorator(get_comps):
        @blueprint.route(path + '/change_competency', methods=['POST'])
        def change_competency(**kwargs):
            change_competency_func()
            return jsonify(table=render_table(get_comps(**kwargs), get_current_work()))
        return change_competency
    return decorator

employer/blueprints/employer.py
from flask import Blueprint, render_template
from services_info import get_employer_info, get_current_user, get_employer_works
from flask_security import login_required

employer_page = Blueprint('employer_page', __name__, template_folder='templates')


@employer_page.route('/employer/<int:employer_id>')
@login_required
def employer(employer_id: int):
    return render_template("employer.html",
                           user=get_current_user(),
                           employer=get_employer_info(employer_id),
                           works=get_employer_works(employer_id))

employer/blueprints/main.py
from flask import Blueprint, render_template, redirect, url_for
from services_info import get_current_user, get_current_user_id, get_employer_works
from flask_security import login_required, logout_user

main_page = Blueprint('main_page', __name__, template_folder='templates')


@main_page.route('/')
@login_required
def index():
    return render_template("index.html", user=get_current_user(), works=get_employer_works(get_current_user_id()))


@main_page.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('/'))

employer/blueprints/manage_competencies.py
from flask import Blueprint, render_template, jsonify, request, render_template_string
from services_info import get_current_user, get_professions, get_competencies, get_areas, get_area_profs, get_work_info
from .competency_table import render_table, change_competency_func, get_current_work
from flask_security import login_required

manage_competencies_page = Blueprint('manage_competencies_page', __name__, template_folder='templates')


@manage_competencies_page.route('/manage_competencies/<int:work_id>')
@login_required
def manage_competencies(work_id: int):
    return render_template("manage_competencies.html", user=get_current_user(), work=get_work_info(work_id),
                           professions=get_professions(), areas=get_areas())


def get_found_comps():
    form = request.form
    prof_id = form.get('prof_id', 0, type=int)
    area_id = form.get('area_id', 0, type=int)
    description = form.get('description', None, type=str)
    return get_competencies(area_id, prof_id, description)


@manage_competencies_page.route('/change_competency', methods=['POST'])
@login_required
def change_competency():
    change_competency_func()
    found_comps = get_found_comps()
    work = get_current_work()
    return jsonify(
        found_comp_table=render_table(found_comps, work),
        user_comp_table=render_table(None, work)
    )


_option_template = "{% import 'profession_select.html' as macro %}{{ macro.profession_select(professions, disabled) }}"


@manage_competencies_page.route('/get_prof_comps', methods=['POST'])
@login_required
def get_prof_comps():
    form = request.form
    area_id = form.get('area_id', 0, type=int)
    update_prof = form.get('update_prof', False, type=bool)

    found_comp_table = render_table(get_found_comps(), get_current_work())

    if update_prof:
        return jsonify(
            found_comp_table=found_comp_table,
            prof_select=render_template_string(_option_template, professions=get_area_profs(area_id), disabled=area_id == 0)
        )
    else:
        return jsonify(found_comp_table=found_comp_table)

employer/blueprints/work.py
from flask import Blueprint, render_template
from services_info import get_work_info, get_current_user
from flask_security import login_required

work_page = Blueprint('work_page', __name__, template_folder='templates')


@work_page.route('/work/<int:work_id>')
@login_required
def work(work_id: int):
    return render_template("work.html", user=get_current_user(), work=get_work_info(work_id))

employer/blueprints/worker.py
from flask import Blueprint, render_template
from services_info import get_current_user, get_worker_info
from .competency_table import load_table, get_current_work
from flask_security import login_required

worker_page = Blueprint('worker_page', __name__, template_folder='templates')


@worker_page.route('/worker/<int:worker_id>')
@login_required
def worker(worker_id: int):
    return render_template("worker.html", user=get_worker_info(worker_id), worker=get_worker_info(worker_id),
                           work=get_current_work(from_args=True))


@load_table(worker_page, '/worker/<int:worker_id>')
@login_required
def change_competency(worker_id: int):
    return get_worker_info(worker_id)['competencies']

employer/templates/add_work.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Создание вакансии
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
        <h1>Создание вакансии</h1>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-xs-2"></div>
</div>
{% endblock %}

employer/templates/base.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main_page.index') }}">Компетентностная система</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main_page.index') }}">Профиль</a></li>
                    <li><a href="{{ url_for('main_page.logout') }}">Выход</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

employer/templates/best_workers.html
{% extends "base.html" %}
{% import 'works_table.html' as macro %}

{% block title %}
    Подходящие соискатели
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Наиболее подходящие соискатели</h3>
        <div>
            {% if best_workers %}
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Имя</th>
                        <th>Изученные компетенции</th>
                    </tr>
                </thead>
                <tbody>
                {% for worker in best_workers %}
                    <tr>
                        <td><a href="{{ url_for('worker_page.worker', worker_id=worker.id, work=work_id) }}">{{ worker.name }}</a></td>
                        <td>
                            <ul style="list-style-position: inside; padding-left: 0;">
                            {% for competency in worker.competencies %}
                                <li><a href="{{ url_for('competency_page.competency', comp_id=competency.id, work=work_id) }}">{{ competency.name }}</a></li>
                            {% endfor %}
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>Соискатели отсутствуют</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

employer/templates/comp_table.html
{% macro div_table(view_competencies, added_competencies, div_name='competencies_table', work_id=none) %}
<div id="{{ div_name }}">
    {{ table(view_competencies, added_competencies, work_id=work_id) }}
</div>
{% endmacro %}

{% macro table(view_competencies, added_competencies, active=true, work_id=none) %}
{% if view_competencies %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Компетенция</th>
            <th>Индикаторы компетенции</th>
            {% if active %}
            <th></th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% if active %}{% set added_competencies = added_competencies | to_set %}{% endif %}
        {% for competency in view_competencies %}
        <tr>
            <td><a href="{{ url_for('competency_page.competency', comp_id=competency.id, work=work_id) }}">{{ competency.name }}</a></td>
            <td>
            <ul style="list-style-position: inside; padding-left: 0;">
                {% for indicator in competency.indicators[:5] %}
                    <li>{{ indicator }}</li>
                {% endfor %}
            </ul>
            </td>
            {% if active %}
            <td>
                {% if added_competencies is none or competency.id in added_competencies %}
                    <button class="btn btn-default" type="button" onclick="change_competency('remove', {{ competency.id }})">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <span><strong>Удалить</strong></span>
                    </button>
                {% else %}
                    <button class="btn btn-default" type="button" onclick="change_competency('append', {{ competency.id }})">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        <span><strong>Добавить</strong></span>
                    </button>
                {% endif %}
            </td>
            {% endif %}
        </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>Выбранные компетенции отсутствуют</p>
{% endif %}
{% endmacro %}

{% macro table_changed(work_id, div_name='competencies_table') %}
<script>
    function change_competency(type, comp_id) {
        $.ajax({
            method: 'POST',
            url: '{{ request.path }}/change_competency',
            data: {type: type, comp_id: comp_id, work_id: {{ work_id }}}
        }).done(function(data){
            $('#{{ div_name }}').html(data.table);
        });
    }
</script>
{% endmacro %}

employer/templates/competency.html
{% extends "base.html" %}

{% block title %}
    Компетенция &mdash; {{ competency.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Компетенция &mdash; {{ competency.name }}</h3>

        <ul>
        {% for indicator in competency.indicators %}
            <li>{{ indicator }}</li>
        {% endfor %}
        </ul>

        {% if work %}
        {% set added = (competency.id in work.competencies) %}

        <div id="is_added" {% if not added %} style="display:none;" {% endif %}>
            <p>Вакансия <a href="{{ url_for('work_page.work', work_id=work.id) }}">{{ work.description }}</a> требует данную компетенцию</p>
            <button class="btn btn-default" type="button" onclick="change_competency('remove', {{ competency.id }})">
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <span><strong>Удалить</strong></span>
            </button>
        </div>
        <div id="is_not_added" {% if added %} style="display:none;" {% endif %}>
            <p>Вакансия <a href="{{ url_for('work_page.work', work_id=work.id) }}">{{ work.description }}</a> не требует данную компетенцию</p>
            <button class="btn btn-default" type="button" onclick="change_competency('append', {{ competency.id }})">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <span><strong>Добавить</strong></span>
            </button>
        </div>
        {% endif %}

    </div>
{% endblock %}


{% if work %}
{% block scripts %}
    {{ super() }}
    <script type=text/javascript>
        function change_competency(type, comp_id) {
            $.ajax({
                method: 'POST',
                url: {{ url_for('competency_page.change_competency_1')|tojson }},
                data: {type: type, comp_id: comp_id, work_id: {{ work.id }}}
            }).done(function(data) {
                let is_added = data.is_added;
                $('#is_added').toggle(is_added);
                $('#is_not_added').toggle(!is_added);
            });
        }
    </script>
{% endblock %}
{% endif %}

employer/templates/employer.html
{% extends "base.html" %}
{% import 'works_table.html' as macro %}

{% block title %}
    Работодатель &mdash; {{ employer.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <h3>{{ employer.name }}</h3>
        <p>{{ employer.description }}</p>
        <h4>Вакансии</h4>
        {{ macro.table(works) }}
    </div>
{% endblock %}

employer/templates/index.html
{% extends "base.html" %}
{% import 'works_table.html' as macro %}

{% block title %}
    Система управления компетенциями
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Здравствуй, {{ user.name }}!</h2>

        <a href="{{ url_for('add_work_page.add_work') }}" class="btn btn-default">
            <strong>Создать новую вакансию</strong>
        </a>

        <h3>Ваши вакансии</h3>
        {{ macro.table(works) }}

    </div>
{% endblock %}

employer/templates/manage_competencies.html
{% extends "base.html" %}
{% import 'comp_table.html' as comp_table %}
{% import 'profession_select.html' as prof_select %}

{% block title %}
    Система управления компетенциями
{% endblock %}

{% block content %}
<div class="container">
    <h3>Выбранные для вакансии компетенции</h3>
    {{ comp_table.div_table(work.competencies, none, 'user_comp_table', work_id=work.id) }}

    <h3>Поиск компетенций</h3>
    <div class="form-group">
        <select id="area-selector" class="form-control">
            <option value="0">Выберите профессиональную область</option>
            {% for area in areas %}
                <option value="{{ area.id }}">{{ area.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div id="prof-selector-div" class="form-group"></div>
    <div class="form-group">
        <textarea id="comp-text" class="form-control" placeholder="Введите описание компетенции своими словами"></textarea>
    </div>
    <div class="form-group">
        <button id="search-button" class="btn btn-default" type="button" onclick="on_prof_selector_change()">Поиск</button>
    </div>

    {{ comp_table.div_table([], none, 'found_comp_table', work.id) }}

</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script type=text/javascript>
    $('#prof-selector').change(on_prof_selector_change);
    $('#area-selector').change(on_area_selector_change).change();

    function on_prof_selector_change() {
        ajax_update_tables({prof_id: $('#prof-selector').val()});
    }

    function on_area_selector_change() {
        ajax_update_tables({update_prof: true});
    }

    function ajax_update_tables(data) {
        data.area_id = $('#area-selector').val();
        data.description = $('#comp-text').val();
        data.work_id = {{ work.id }};
        $('#search-button').prop("disabled", true);
        $.ajax({
            method: 'POST',
            url: {{ url_for('manage_competencies_page.get_prof_comps')|tojson }},
            data: data
        }).done(update_tables);
    }

    function update_tables(data) {
        $('#found_comp_table').html(data.found_comp_table);
        if (data.hasOwnProperty('user_comp_table')) {
            $('#user_comp_table').html(data.user_comp_table);
        }
        if (data.hasOwnProperty('prof_select')) {
            $('#prof-selector-div').html(data.prof_select);
            $('#prof-selector').change(on_prof_selector_change);
        }
        $('#search-button').prop("disabled", false);
    }

    function change_competency(type, comp_id) {
        $('#search-button').prop("disabled", true);
        $.ajax({
            method: 'POST',
            url: {{ url_for('manage_competencies_page.change_competency')|tojson }},
            data: {type: type, comp_id: comp_id, work_id: {{ work.id }},
                prof_id: $('#prof-selector').val(), area_id: $('#area-selector').val()}
        }).done(update_tables);
    }
</script>
{% endblock %}

employer/templates/profession_select.html
{% macro profession_select(professions, disabled=false) %}
<select id="prof-selector" class="form-control" {% if disabled %}disabled{% endif %}>
    <option value="0">{% if disabled %}Выберите профессиональную область{% else %}Выберите профессию{% endif %}</option>
    {% for profession in professions %}
    <option value="{{ profession.id }}">{{ profession.name }}</option>
    {% endfor %}
</select>
{% endmacro %}

employer/templates/work.html
{% extends "base.html" %}
{% import 'comp_table.html' as macro %}

{% block title %}
    Вакансия &mdash; {{ work.description }}
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Вакансия &mdash; {{ work.description }}</h3>

        <p><b>Зарплата:</b> {{ work.salary }}₽</p>

        <div class="btn-group-vertical">
            <a href="{{ url_for('manage_competencies_page.manage_competencies', work_id=work.id) }}" class="btn btn-default">
                <strong>Выбрать компетенции для вакансии</strong>
            </a>
            <a href="{{ url_for('best_workers_page.best_workers', work_id=work.id) }}" class="btn btn-default">
                <strong>Найти наиболее подходящих соискателей</strong>
            </a>
        </div>

        <h4>Требуемые для вакансии компетенции</h4>
        {{ macro.table(work.competencies, none, false, work.id) }}
    </div>
{% endblock %}

employer/templates/worker.html
{% extends "base.html" %}
{% import 'comp_table.html' as macro %}

{% block title %}
    Система управления компетенциями
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Соискатель {{ user.name }}!</h2>

        <h3>Компетенции соискателя</h3>
        {% if work %}
            {{ macro.div_table(user.competencies, work.competencies, work_id=work.id) }}
        {% else %}
            {{ macro.table(user.competencies, none, false) }}
        {% endif %}

    </div>
{% endblock %}

{% if work %}
{% block scripts %}
    {{ super() }}
    {{ macro.table_changed(work.id) }}
{% endblock %}
{% endif %}

employer/templates/works_table.html
{% macro table(works) %}
{% if works %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Вакансия</th>
            <th>Необходимые компетенции</th>
            <th>Зарплата</th>
        </tr>
    </thead>
    <tbody>
    {% for work in works %}
        <tr>
            <td><a href="{{ url_for('work_page.work', work_id=work.id) }}">{{ work.description }}</a></td>
            <td>
                <ul style="list-style-position: inside; padding-left: 0;">
                {% for competency in work.competencies %}
                    <li><a href="{{ url_for('competency_page.competency', comp_id=competency.id, work=work.id) }}">{{ competency.name }}</a></li>
                {% endfor %}
                </ul>
            </td>
            <td>{{ work.salary }}₽</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Вакансии отсутствуют</p>
{% endif %}
{% endmacro %}